---
title: "Heirarchical Cluster"
author: "Mandy Liesch"
date: "12/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
library(factoextra) # clustering visualization
library(tree)
library(randomForest)
library(caret)
```

```{r}
#load in data frame
df <- read.csv("agIntenSlope.csv")
#Replace the NA with zeros
df[is.na(df)]<-0
#make sure all observations are complete
sum(complete.cases(df)) 
#There are two counties that are extreme outliers (they are intensifying beyond any realm of normal):
df <- df[-c(329, 353, 854, 889), ]

#Set Rownames as GEOID
row.names(df) <- df$誰..GEOID
df$誰..GEOID<-NULL


#scale the data
scaleDF <- scale(df)

# Calculate the Disimilarity Matrix
d <- dist(scaleDF, method = "euclidean")
```

```{r}
# methods to assess
m <- c( "average", "single", "complete", "ward")
names(m) <- c( "average", "single", "complete", "ward")

# function to compute coefficient
ac <- function(x) {
  agnes(scaleDF, method = x)$ac
}

map_dbl(m, ac)

dianaClust <- diana(scaleDF)
dianaClust$dc
```

We are using the Agglomerative Wards linkage method.

```{r}
hc1 <- hclust(d, method = "ward.D2" )
plot(hc1)
rect.hclust(hc1, k = 4, border = 2:5)

sub_grp <- cutree(hc1, k = 4)

table(sub_grp)

df<-df %>%
  mutate(cluster = sub_grp)

df$cluster<-as.factor(df$cluster)
```

```{r}
outTable<-df %>%
  group_by(cluster) %>%
  summarise(mean(totMarkSlope), mean(opgr500kSlope), mean(Adens_Slope), mean(slopelargeCropOp), mean(perMarkSlope))
```

## Baseline Intensity: 1997
```{r}

#load in data frame
df <- read.csv("agIntenInt.csv")
#Replace the NA with zeros
df[is.na(df)]<-0
#make sure all observations are complete
sum(complete.cases(df)) 
#There are two counties that are extreme outliers (they are intensifying beyond any realm of normal):
df <- df[-c(329, 353, 854, 889), ]

#Set Rownames as GEOID
row.names(df) <- df$誰..GEOID
df$誰..GEOID<-NULL


#scale the data
scaleDF <- scale(df)

# Calculate the Disimilarity Matrix
d <- dist(scaleDF, method = "euclidean")
```

```{r}
# methods to assess
m <- c( "average", "single", "complete", "ward")
names(m) <- c( "average", "single", "complete", "ward")

# function to compute coefficient
ac <- function(x) {
  agnes(scaleDF, method = x)$ac
}

map_dbl(m, ac)

dianaClust <- diana(scaleDF)
dianaClust$dc
```

We are using the Agglomerative Wards linkage method.

```{r}
hc1 <- hclust(d, method = "ward.D2" )
plot(hc1)
rect.hclust(hc1, k = 4, border = 2:5)

sub_grp <- cutree(hc1, k = 4)

table(sub_grp)

df<-df %>%
  mutate(cluster = sub_grp)

df$cluster<-as.factor(df$cluster)
```

```{r}
outIntTable<-df %>%
  group_by(cluster) %>%
  summarise(mean(totMarkValue_1997), mean(opgr500k_1997), mean(Adens_Int), mean(opgr2000acres_1997), mean(perBigMark1997))
```
