---
title: "Leaflet Protocol"
author: "Mandy Liesch"
date: "12/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
library(dplyr)
library(ggplot2)
library(rjson)
library(jsonlite)
library(leaflet)
library(RCurl)
library(rgeos)
library(maptools)
library(leaflet)
library(htmltools)
```

```{r}
countyData<-readShapeSpatial("countyshape.shp")
agIntenSlope<-read.csv("agIntenSlope.csv")
agIntenSlope$GEOID<-agIntenSlope$ï..GEOID
agIntenSlope$ï..GEOID<-NULL

dataMap<-merge(countyData, agIntenSlope, by.x="GEOID_1", by.y="GEOID")

pal <- colorNumeric(palette = "Reds", domain = dataMap$totMarkSlope, na.color = NA)

popup <- paste0("<strong>", dataMap$NAME, "</strong><br /> 
            Total Market Value: $", dataMap$totMarkSlope, "<br />
            Operations with Income > $500,000: ", dataMap$opgr500kSlope,  "<br /> Farms > 2000 Acres: ",
dataMap$slopelargeCropOp, "<br /> Animal Density: ", dataMap$Adens_Slope, "<br />
            Percent of Sales > $500,000: ",
dataMap$perMarkSlope)

MapInfo <- tags$p(tags$style("<p {font-size:12px} />"),
            tags$b("Agricultural Intensification: Rate of Change (Slope)"))

dataMap %>% # Inputs data set
    leaflet(width = "100%") %>% # Interactive mapping package
    addProviderTiles(provider = "CartoDB.Positron") %>% # Changes base map
    setView(-98.483330, 38.712046, zoom = 4) %>% 
    addPolygons(popup = ~ popup,
                stroke = FALSE,
                smoothFactor = 0,
                fillOpacity = 0.7,
                color = ~ pal(totMarkSlope)) %>%
    addLegend("bottomright", 
              pal = pal, 
              values = ~ totMarkSlope,
              title = "Total Market Rate of Change",
              opacity = 1) %>% # Creates legend
    addControl(MapInfo, position = "topright")


```
